name: megapose
channels:
   - conda-forge
   - pytorch
   - anaconda
   - defaults
dependencies:
  - python=3.9
  - pip
  - wget
  - python-wget
  - joblib
  - pytorch==1.11.0
  - torchvision==0.12.0
  - cudatoolkit==11.3.1
  - ipython
  - ipykernel
  - jupyterlab
  - notebook==6.4.12
  - nb_conda_kernels
  - jupyter_contrib_nbextensions
  - pinocchio
  - rclone
  - pillow
  - ipywidgets
  - selenium
  - geckodriver
  - firefox
  - pip:
      - meshcat
      - selenium
      - omegaconf
      - simplejson
      - line_profiler 
      - opencv-python
      - torchnet
      - tqdm
      - lxml
      - transforms3d
      - panda3d
      - joblib
      - xarray 
      - pandas
      - matplotlib
      - bokeh
      - plyfile 
      - trimesh 
      - ipdb 
      - panda3d-gltf
      - colorama
      - pyyaml
      - ipykernel
      - scipy
      - pypng
      - h5py 
      - seaborn
      - kornia 
      - pyarrow 
      - dt_apriltags 
      - open3d
      - structlog
      - imageio
      - progressbar
      - pyyaml
      - psutil
      - webdataset
      - opencv-contrib-python 
      - roma 
      - torchgeometry
